### ISSUE TITLE
sqlalchemy version mismatch

### ISSUE THREAD

**Issue by MehdiSfr** [verdan/flaskoidc#34]
Container stops running in both amundsenmetadata and amundsensearch because of this error:
`amundsensearch    | Using requested Flask module flaskoidc and class FlaskOIDC
amundsensearch    | Traceback (most recent call last):
amundsensearch    |   File "search_service/search_wsgi.py", line 15, in <module>
amundsensearch    |     application = create_app(config_module_class=config_module_class)
amundsensearch    |   File "/app/search_service/__init__.py", line 67, in create_app
amundsensearch    |     app = class_obj(__name__, **flask_kwargs_dict)
amundsensearch    |   File "/usr/local/lib/python3.7/site-packages/flaskoidc/__init__.py", line 75, in __init__
amundsensearch    |     self.db = SQLAlchemy(self)
amundsensearch    |   File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
amundsensearch    |     _include_sqlalchemy(self, query_class)
amundsensearch    |   File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
amundsensearch    |     for key in module.__all__:
amundsensearch    | AttributeError: module 'sqlalchemy' has no attribute '__all__'`

looks like to get ride of this we need to upgrade the flask_sqlalchemy to >=3.0.0 which ofcouse  rises dependency conflict and containers can not be built!

**Comment by AykCanDem** [comment]
downgrade SQLAlchemy to 1.3.x. It is not compatible with >=2.0.0.
